# Writes OUT (a .cpp) with the build identity: CMake project VERSION plus
# `git describe --tags --always --dirty`, the commit and the branch of SRC.
# Run on every build (target pando_build_info); OUT only changes when the
# identity does, so nothing recompiles otherwise. Outside a git checkout
# (release tarball, broken alternates) the describe falls back to VERSION.
set(ENV{GIT_OPTIONAL_LOCKS} 0)
set(describe "")
set(commit "unknown")
set(branch "")
find_program(GIT_EXE git)
if(GIT_EXE)
    execute_process(COMMAND ${GIT_EXE} -C ${SRC} describe --tags --always --dirty
                    OUTPUT_VARIABLE describe RESULT_VARIABLE r1
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT r1 EQUAL 0)
        set(describe "")
    endif()
    execute_process(COMMAND ${GIT_EXE} -C ${SRC} rev-parse HEAD
                    OUTPUT_VARIABLE c RESULT_VARIABLE r2
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(r2 EQUAL 0 AND NOT c STREQUAL "")
        set(commit "${c}")
    endif()
    execute_process(COMMAND ${GIT_EXE} -C ${SRC} rev-parse --abbrev-ref HEAD
                    OUTPUT_VARIABLE b RESULT_VARIABLE r3
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(r3 EQUAL 0 AND NOT b STREQUAL "HEAD")
        set(branch "${b}")
    endif()
endif()
if(describe STREQUAL "")
    set(describe "${VERSION}")
endif()
file(WRITE "${OUT}.tmp" "// Generated by cmake/build_info.cmake — do not edit.
#include \"core/build_info.h\"
namespace pando {
const char* build_version() { return \"${VERSION}\"; }
const char* build_describe() { return \"${describe}\"; }
const char* build_commit() { return \"${commit}\"; }
const char* build_branch() { return \"${branch}\"; }
}  // namespace pando
")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
